require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  AllowedGroups:
    - describe
